macro(paperbreak_resolve_dependencies)
    if(DEFINED ENV{PAPERBREAK_QT_ROOT} AND NOT "$ENV{PAPERBREAK_QT_ROOT}" STREQUAL "")
        list(PREPEND CMAKE_PREFIX_PATH "$ENV{PAPERBREAK_QT_ROOT}")
    endif()

    find_package(Qt6 6.10.2 EXACT REQUIRED COMPONENTS Core Gui Widgets Network)
    find_package(OpenCV 4.12.0 EXACT REQUIRED COMPONENTS core imgproc imgcodecs)
    find_package(spdlog 1.17.0 CONFIG REQUIRED)
    find_package(nlohmann_json 3.12.0 CONFIG REQUIRED)
    find_package(SQLite3 3.53.4 REQUIRED)

    if(BUILD_TESTING)
        find_package(GTest 1.17.0 CONFIG REQUIRED)
    endif()

    set(PAPERBREAK_QT_VERSION "${Qt6_VERSION}")
    set(PAPERBREAK_OPENCV_VERSION "${OpenCV_VERSION}")
    set(PAPERBREAK_SPDLOG_VERSION "${spdlog_VERSION}")
    set(PAPERBREAK_JSON_VERSION "${nlohmann_json_VERSION}")
    set(PAPERBREAK_SQLITE_VERSION "${SQLite3_VERSION}")
endmacro()
